<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add option' => 'Добавить опцию',
    'Additionally' => 'Дополнительно',
    'Are you sure you want to delete this category?' => 'Вы уверены, что хотите удалить эту категорию?',
    'Edit' => 'Изменить',
    'Edit property' => 'Изменить свойство',
    'Enter product name...' => 'Введите название товара...',
    'New category' => 'Новая категория',
    'New option' => 'Новая опция',
    'New product' => 'Новый товар',
    'New property' => 'Новое свойство',
    'Open' => 'Открыть',
    'Options' => 'Опции',
    'Products' => 'Товары',
    'Properties' => 'Свойства',
    'Remove' => 'Удалить',
    'Remove option' => 'Удалить опцию',
    'Save' => 'Сохранить',
];
