<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add price' => 'Наценка',
    'Address' => 'Адрес',
    'Addressee' => 'Получатель',
    'Addressee e-mail' => 'E-mail получателя',
    'Addressee name' => 'Имя получателя',
    'Addressee phone' => 'Телефон получателя',
    'Brand' => 'Бренд',
    'Categories' => 'Категории',
    'Category ID' => 'ID категории',
    'Category cannot be nested in itself' => 'Категория не может быть вложена в саму себя',
    'Count' => 'Количество',
    'Cover' => 'Обложка',
    'Created at' => 'Создано',
    'Delivery method' => 'Способ доставки',
    'Description' => 'Описание',
    'Discount' => 'Скидка',
    'E-mail' => 'E-mail',
    'Favorite' => 'Избранное',
    'Group' => 'Группа',
    'Group code' => 'Код группы',
    'Group name' => 'Название группы',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Key' => 'Ключ',
    'Link' => 'Ссылка',
    'Linked Product ID' => 'ID связанного товара',
    'Logo' => 'Логотип',
    'Name' => 'Название',
    'Option' => 'Опция',
    'Option ID' => 'ID опции',
    'Options' => 'Опции',
    'Order' => 'Порядок',
    'Order Product ID' => 'ID товара в заказе',
    'Order from site' => 'Заказ с сайта',
    'Order num' => 'Номер заказа',
    'Parent category' => 'Родительская категория',
    'Payment method' => 'Способ оплаты',
    'Phone' => 'Телефон',
    'Price' => 'Цена',
    'Product' => 'Товар',
    'Product ID' => 'ID товара',
    'Product Option ID' => 'ID опции товара',
    'Products' => 'Товары',
    'Property' => 'Свойство',
    'Property ID' => 'ID свойства',
    'Property groups' => 'Группы свойства',
    'Relation ID' => 'ID связи',
    'SKU' => 'Артикул',
    'Seo Description' => 'Seo-описание',
    'Seo Title' => 'Seo-заголовок',
    'Seo Url' => 'Seo-url',
    'Short description' => 'Краткое описание',
    'Status' => 'Статус',
    'Sticker' => 'Стикер',
    'Stickers' => 'Стикеры',
    'Sum' => 'Сумма',
    'Type' => 'Тип',
    'Use in filter' => 'Использовать в фильтре',
    'Value' => 'Значение',
    'apt.' => 'кв.',
    'block' => 'блок',
    'building' => 'строение',
    'house' => 'д.',
    'pcs.' => 'шт.',
    'st.' => 'ул.',
    'Available in stock' => 'Есть в наличии',
];
