<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to remove an item from your cart?' => 'Вы уверены, что хотите удалить товар из корзины?',
    'Can\'t add this product to cart' => 'Невозможно добавить этот товар в корзину',
    'Cancel' => 'Отмена',
    'Cart' => 'Корзина',
    'Continue shopping' => 'Продолжить покупки',
    'Count' => 'Кол-во',
    'Error adding to cart' => 'Невозможно добавить в корзину',
    'Order from site' => 'Заказ с сайта',
    'Price' => 'Цена',
    'Product' => 'Товар',
    'Remove' => 'Удалить',
    'Sum' => 'Сумма',
    'Thak you for your order! Our manager will call you back soon.' => 'Спасибо за ваш заказ! Наш менеджер перезвонит вам в ближайшее время.',
    'Total:' => 'Итого:',
    'You must fill all required fields' => 'Необходимо заполнить все обязательные поля',
    'Your order' => 'Вы заказали',
	'Order sent' => 'Заказ отправлен',
    'Order error' => 'Ошибка заказа',
    'An unexpected error occurred while submitting your order. Please go {cart_link} and resend your order. We apologize for any inconvenience caused.' => 'При отправке заказа произошла непредвиденная ошибка. Пожалуйста, перейдите {cart_link} и попробуйте повторить отправку вашего заказа. Приносим извинения за доставленные неудобства.',
    'to cart' => 'в корзину',
];
